### ISSUE TITLE
The space is underlined 

### ISSUE THREAD

**Issue by UncringeUsername** [OWelton-Rosie/My-code#2]
![image](https://github.com/user-attachments/assets/52cd8cae-6f61-464a-a0ce-f86bb034801c)

This has been keeping me up at night, and is making me feel very stressed. I would greatly appreciate it if you could fix this major issue within the next shortish time period. Thanks in advance. 🤫 🧏‍♂️

**Comment by OWelton-Rosie** [comment]
@UncringeUsername It's fixed. For more info, click [here](https://github.com/OWelton-Rosie/My-code/commit/41f3af1f00df56aacd5279f7d1afa6236a9e7819)

**Comment by UncringeUsername** [comment]
[file:///C:/Users/thoma/Downloads/My-code.html](url) test

**Comment by UncringeUsername** [comment]
[test](file:///C:/Users/thoma/Downloads/My-code.html)

**Comment by UncringeUsername** [comment]
[test](https://www.youtube.com/watch?v=eJoViV5T1g0)
